name: Build Windows Game
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3' # Or whichever Qt 6 version you are using
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Configure CMake
      run: cmake -B build -G "MinGW Makefiles"

    - name: Build Game
      run: cmake --build build

    - name: Run windeployqt
      run: |
        mkdir release_folder
        copy build\QtMonopoly.exe release_folder\
        windeployqt release_folder\QtMonopoly.exe

    - name: Upload Windows Game
      uses: actions/upload-artifact@v3
      with:
        name: QtMonopoly-Windows
        path: release_folder/